#!/bin/bash



SOURCE_DIRS=("" conf dynval model tests)

which godep &>/dev/null || go get

godep restore

while :; do
    OUTPUT=$(godep save "${SOURCE_DIRS[@]/#/github.com/appwilldev/Instafig/}" 2>&1)
    [ "$OUTPUT" = "" ] && break
    OUTPUT=${OUTPUT#*\(}
    OUTPUT=${OUTPUT%\)*}
    echo go get $OUTPUT
    go get $OUTPUT
done

if [ "$1" = update-version ]; then
    godep update
fi
