#!/bin/bash



SOURCE_DIRS=("" conf dynval model tests)

which godep &>/dev/null || go get github.com/tools/godep

#godep restore

while :; do
    OUTPUT=$(godep save "${SOURCE_DIRS[@]/#/github.com/appwilldev/Instafig/}" 2>&1)
    [ "$OUTPUT" = "" ] && break
    OUTPUT=${OUTPUT#*\(}
    OUTPUT=${OUTPUT%\)*}
    echo go get $OUTPUT
    go get $OUTPUT
    [ $? = 0 ] || {
        echo "error on `go get $OUTPUT`"
        exit 1
    }
done

if [ "$1" = update-version ]; then
    godep update
fi
