#!/bin/bash
# -*- mode: sh -*-

KERNEL=$(tr [:upper:] [:lower:] <<< $(uname -s))
DEST_PATH=/nightly/Instafig/${TRAVIS_BUILD_NUMBER}/Instafig.${KERNEL}

\curl http://cxan.kdr2.com/pkg-c.php -F file=@../../../../bin/Instafig -F dest=${DEST_PATH} -F token=${CXAN_TOKEN}
